service: serverless-todo-app

plugins:
  - serverless-iam-roles-per-function

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x

functions:
  Auth:
    handler: dist/lambda/auth/auth0Authorizer.handler

  GetTodos:
    handler: dist/lambda/http/getTodos.handler
    events:
      - http:
          method: get
          path: todos

  CreateTodo:
    handler: dist/lambda/http/createTodo.handler
    events:
      - http:
          method: post
          path: todos

  UpdateTodo:
    handler: dist/lambda/http/updateTodo.handler
    events:
      - http:
          method: patch
          path: todos/{todoId}

  DeleteTodo:
    handler: dist/lambda/http/deleteTodo.handler
    events:
      - http:
          method: delete
          path: todos/{todoId}

  GenerateUploadUrl:
    handler: dist/lambda/http/generateUploadUrl.handler
    events:
      - http:
          method: post
          path: todos/{todoId}/attachment

resources:
  Resources:
    # Add any necessary AWS resources
